export * as userService from './user.service'
export * as authService from './auth.service'
export * as tokenService from './token.service'
export * as emailService from './email.service'
export * as uploadService from './upload.service'
export * as sinhVienService from './sinh-vien.service'
export * as lopService from './lop.service'
export * as khoaService from './khoa.service'
export * as monHocService from './mon-hoc.service'
export * as ketQuaService from './ket-qua.service'
export * as baiTapService from './bai-tap.service'

export * as baiKiemTraService from './2_Chiu-Cam-Minh_13.service'
